
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-01T09:27:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "73be67c88cfa32f0d41cfe58ba9750b4d863805a",
 "version": "4.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
